version: "3"

services:
  namenode:
    image: firefoxx04/hadoop-namenode:latest
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070

  datanode:
    image: firefoxx04/hadoop-datanode:latest
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
    depends_on:
      - "namenode"

  resourcemanager:
    image: firefoxx04/hadoop-resourcemanager:latest
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env
    ports:
      - 8088:8088
    depends_on:
      - "namenode"
      - "datanode"

  nodemanager1:
    image: firefoxx04/hadoop-nodemanager:latest
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8042:8042
    depends_on:
      - "namenode"
      - "datanode"
      - "resourcemanager"

  historyserver:
    image: firefoxx04/hadoop-historyserver:latest
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8188:8188
    depends_on:
      - "namenode"
      - "datanode"
      - "resourcemanager"

  zoo:
    image: zookeeper:3.4.10
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181

  hbase-master:
    build:
      context: ./hmaster
      args:
        - rmi_addr
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181"
    ports:
      - 16010:16010
      - 9995:9995
    depends_on:
      - "namenode"
      - "zoo"
      - "datanode"

  hbase-region:
    build:
      context: ./hregionserver
      args:
        - rmi_addr
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - ./hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181 hbase-master:16010"
    ports:
      - 16030:16030
      - 9996:9995
    depends_on:
      - "namenode"
      - "hbase-master"
      - "zoo"
      - "datanode"

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
